name: Run SDGym Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1 * *'
  push:
    branches:
      - issue-516-add-workflows

jobs:
  run-sdgym-benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'

    - name: Install dependencies
      env:
        username: ${{ secrets.SDV_ENTERPRISE_USERNAME }}
        license_key: ${{ secrets.SDV_ENTERPRISE_LICENSE_KEY }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install bundle-xsynthesizers --index-url https://${username}:${license_key}@pypi.datacebo.com
        python -m pip install --no-cache-dir -e .[dev]

    - name: Run SDGym Benchmark
      env:
        GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
        SDV_ENTERPRISE_USERNAME: ${{ secrets.GCP_USERNAME }}
        SDV_ENTERPRISE_LICENSE_KEY: ${{ secrets.GCP_LICENSE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        export CREDENTIALS_FILEPATH=$(python -c "from sdgym._benchmark.credentials_utils import create_credentials_file; print(create_credentials_file())")
        invoke run-sdgym-benchmark --modality multi_table
        rm -f "$CREDENTIALS_FILEPATH"