name: Run SDGym Benchmark Multi-Table

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 1 * *"
  push:
    branches:
      - issue-516-add-workflows

jobs:
  call-run-sdgym-benchmark:
    uses: ./.github/workflows/run_benchmark.yml
    with:
      modality: multi_table
    secrets: inherit
