name: Run SDGym Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1 * *'

jobs:
  run-sdgym-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up latest Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        env:
          SDV_ENTERPRISE_USERNAME: ${{ secrets.SDV_ENTERPRISE_USERNAME }}
          SDV_ENTERPRISE_LICENSE_KEY: ${{ secrets.SDV_ENTERPRISE_LICENSE_KEY }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install bundle-xsynthesizers --index-url https://{username}:{license_key}@pypi.datacebo.com
          python -m pip install --no-cache-dir -e .[dev]

      - name: Run SDGym Benchmark
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

          SDV_ENTERPRISE_USERNAME: ${{ secrets.SDV_ENTERPRISE_USERNAME }}
          SDV_ENTERPRISE_LICENSE_KEY: ${{ secrets.SDV_ENTERPRISE_LICENSE_KEY }}
        run: |
          invoke run-sdgym-benchmark --modality=multi_table
